version: "3"
services:
  support-tools:
    build: .
    ports:
      - "3001:3000"
    container_name: support-tools
    volumes:
      - ./support-tools:/usr/src/app/next
      - /usr/src/app/next/node_modules
    command: yarn run build

  sample-function:
    tty: true
    build: 
      context: ./lambda/SampleFunction/
      dockerfile: Dockerfile
    ports:
      - 9000:8080
    environment:
      - AWS_DEFAULT_REGION="ap-northeast-1"
      - AWS_ACCESS_KEY_ID="<your-aws-access-key-id>"
      - AWS_SECRET_ACCESS_KEY="<your-aws-secret-acess-key>"
      - DB_DATABASE=hello_flask_dev
      - DB_USER=hello_flask
      - DB_PASS=hello_flask
      - HOST_NAME=old-support-tools_db_1
    # command: /entry.sh /main

  swagger-editor:
      image: swaggerapi/swagger-editor
      container_name: "swagger-editor"
      ports:
        - "10081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "10082:8080"
    volumes:
      - ./mockServer/openapi.yml:/usr/share/nginx/html/api_reference.yaml
    environment:
      API_URL: api_reference.yaml
  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "10083:4010"
    command: mock -h 0.0.0.0 /api_reference.yaml
    volumes:
      - ./mockServer/openapi.yml:/api_reference.yaml

# oldと同一のDBを使うようにnetworkを設定する
# networks:
#   default:
#     name: old-support-tools_default
#     external: true
